# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19lfcbKcWmncdV5WzVdcCN7eDBvrhGokw
"""

import matplotlib.pyplot as plt
import numpy as np
x=np.linspace(0,5,90)
print(x)
y=4+2 * np.sin(2 * x)
print (y)
fig, ax=plt.subplots()
ax.plot(x, y, linewidth=2.0)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
np.random.seed(3)
x=6+np.random.normal(0,4,30)
y=6+np.random.normal(0,4,len(x))
sizes=np.random.uniform(20, 90, len(x))
colors=np.random.uniform(20, 90, len(x))
fig,ax=plt.subplots()
ax.scatter(x,y,s=sizes, c=colors, vmin=0, vmax=200)
ax.set(xlim=(0,10), xticks=np.arange(1,10),
       ylim=(0,8), yticks=np.arange(1,10))
plt.show()