# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X1Pi1iUrsyB85CNGkIpjCfMbzqX6dPZc
"""



pip install opencv-python

from google.colab.patches import cv2_imshow
 import cv2
 rasm=cv2.imread("mohira1.jpg")
 cv2_imshow(rasm)

oqqora=cv2.cvtColor(rasm,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora )

from google.colab.patches import cv2_imshow
import cv2
rasm=cv2.imread("mohira2.jpg")
cv2_imshow(rasm)

oqqora=cv2.cvtColor(rasm,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora )

from google.colab.patches import cv2_imshow
import cv2
rasm=cv2.imread("mohira3.jpg")
cv2_imshow(rasm)

oqqora=cv2.cvtColor(rasm,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora )